### ISSUE TITLE
How can I find TW server opcode?

### ISSUE THREAD

**Issue by hap0328** [Owyn/let-me-fish#2]
I use "alex-packet-id-finder" or "debug-logger" to find TW server opcode, but never success gets opcode or packet-id....
I watch debug-logger file's content, have not any about "S_FISHING_BITE" or other protocol name.

**Comment by Owyn** [comment]
you have to do installation steps first to have defs in needed folder,

and debug-logger won't show any names, only numbers, it's you who should make link by guessing which is S_FISHING_BITE
